### ISSUE TITLE
能否支持API KEY？

### ISSUE THREAD

**Issue by lmuiotctf** [helianthuswhite/chatgpt-web-next#2]
目前我看仅支持token，建议支持key比较简单

**Comment by helianthuswhite** [comment]
目前的token是提供了一种简单的权限控制策略，避免服务地址泄露导致账户额度被白嫖。如果个人有API KEY的话，可以通过 railway 使用自己的api key单独部署一个，https://railway.app/template/-4ukN3?referralCode=ZtthnC。

之所以没有考虑支持在线填入API Key的方式，是从用户角度考虑，把自己的API Key传给他人一是有风险，二是没有太大必要。
