### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adminlove520** [helianthuswhite/chatgpt-web-next#3]
亲爱的开发者~请问有计划扩展加入replicate、sd这些AI绘画的组件嘛。

**Comment by helianthuswhite** [comment]
会的哈，预计本周或者下周就会增加 sd 的绘图能力。

**Comment by adminlove520** [comment]
> 会的哈，预计本周或者下周就会增加 sd 的绘图能力。

您可以参考这个仓库https://github.com/zhayujie/chatgpt-on-wechat/    、https://github.com/db0/AI-Horde
sd的话用AI-Horde  可选的model还行 但是速度会慢一些；replicate绘图速度快一些，对二次元图好一点，人像不太好

**Comment by adminlove520** [comment]
本地API和谷歌云我试过，效果都不是很棒   可以考虑插件化

**Comment by adminlove520** [comment]
main分支的login、email注册这些接口必须要配置API_REVERSE_PROXY嘛？本地部署登录报了500的错
```
2023-04-20T08:43:09.955Z [api-proxy] info: /api/v1/user/verify/send_code {"email":"***@qq.com"}
error - Error: Must provide a proper URL as target
```

**Comment by helianthuswhite** [comment]
本地部署的话使用no-sql分支吧，不需要登录的，也不依赖后端服务，只需要填入 API_KEY 和代理就行了。
main分支依赖后端服务，目前我们的后端服务还未开源，这个项目的main分支只有 https://chatalpha.top/ 的前端部分。
